"""Add STLModel table

Revision ID: 501c7cb9ab5d
Revises: e260f0eac018
Create Date: 2025-06-11 20:29:28.799223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501c7cb9ab5d'
down_revision = 'e260f0eac018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stl_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['gebruiker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stl_model')
    # ### end Alembic commands ###
