"""Добавление поля is_private и таблицы Follow

Revision ID: 52c6b9ad043b
Revises: c11e421ea180
Create Date: 2025-06-12 16:32:45.804839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c6b9ad043b'
down_revision = 'c11e421ea180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['gebruiker.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['gebruiker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='_follower_followed_uc')
    )
    with op.batch_alter_table('gebruiker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gebruiker', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    op.drop_table('follow')
    # ### end Alembic commands ###
