"""Add location and tags to STLModel

Revision ID: c11e421ea180
Revises: 501c7cb9ab5d
Create Date: 2025-06-12 13:15:49.463907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c11e421ea180'
down_revision = '501c7cb9ab5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    with op.batch_alter_table('gebruiker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.alter_column('profile_picture_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('gebruiker_parent_id_fkey'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('stl_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=200), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl_model', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('tags')
        batch_op.drop_column('location')

    with op.batch_alter_table('gebruiker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('gebruiker_parent_id_fkey'), 'gebruiker', ['parent_id'], ['id'])
        batch_op.alter_column('profile_picture_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('bio')
        batch_op.drop_column('full_name')

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stl_file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['gebruiker.id'], name=op.f('post_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_pkey'))
    )
    # ### end Alembic commands ###
